#!/usr/bin/env python3
"""
YouTube Cookies Manager - 管理 YouTube cookies 转换和验证

支持从 BestCookier 导出的 JSON 格式转换为：
- Playwright storage_state.json（用于 agent-browser）
- Netscape cookies.txt（用于 yt-dlp/curl）
"""

import json
import sys
from datetime import datetime
from pathlib import Path


class YouTubeCookiesManager:
    """YouTube Cookies 管理器"""

    def __init__(self, input_file=None):
        """
        初始化管理器

        Args:
            input_file: BestCookier 导出的 JSON 文件路径
        """
        self.input_file = input_file
        self.cookies = None

    def load_bestcookier_json(self, file_path):
        """
        加载 BestCookier 导出的 JSON cookies

        Args:
            file_path: JSON 文件路径

        Returns:
            bool: 是否成功加载
        """
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                self.cookies = json.load(f)
            print(f"✅ 成功加载 {len(self.cookies)} 个 cookies")
            return True
        except FileNotFoundError:
            print(f"❌ 文件不存在: {file_path}")
            return False
        except json.JSONDecodeError as e:
            print(f"❌ JSON 解析错误: {e}")
            return False

    def convert_to_playwright(self, output_file):
        """
        转换为 Playwright storage_state.json 格式

        Args:
            output_file: 输出文件路径

        Returns:
            bool: 是否成功转换
        """
        if not self.cookies:
            print("❌ 请先加载 cookies")
            return False

        storage_state = {
            "cookies": [],
            "origins": []
        }

        for cookie in self.cookies:
            playwright_cookie = {
                "name": cookie["name"],
                "value": cookie["value"],
                "domain": cookie["domain"],
                "path": cookie["path"],
                "expires": cookie.get("expirationDate", -1),
                "httpOnly": cookie.get("httpOnly", False),
                "secure": cookie.get("secure", False),
                "sameSite": self._normalize_same_site(cookie.get("sameSite", "unspecified"))
            }

            storage_state["cookies"].append(playwright_cookie)

        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(storage_state, f, indent=2, ensure_ascii=False)

        print(f"✅ Playwright 格式已保存: {output_file}")
        return True

    def convert_to_netscape(self, output_file):
        """
        转换为 Netscape cookies.txt 格式

        Args:
            output_file: 输出文件路径

        Returns:
            bool: 是否成功转换
        """
        if not self.cookies:
            print("❌ 请先加载 cookies")
            return False

        with open(output_file, 'w', encoding='utf-8') as f:
            # 写入 Netscape cookie 文件头
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by YouTube Access Skill\n")
            f.write("\n")

            for cookie in self.cookies:
                # Netscape 格式字段：
                # domain - domain flag - path - secure - expiration - name - value
                domain = cookie['domain']
                domain_flag = "TRUE" if domain.startswith('.') else "FALSE"
                path = cookie['path']
                secure = "TRUE" if cookie['secure'] else "FALSE"
                expiration = int(cookie.get("expirationDate", -1))
                name = cookie['name']
                value = cookie['value']

                f.write(f"{domain}\t{domain_flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")

        print(f"✅ Netscape 格式已保存: {output_file}")
        return True

    def validate_cookies(self):
        """
        验证 cookies 的完整性

        Returns:
            dict: 验证结果
        """
        if not self.cookies:
            return {"valid": False, "message": "未加载 cookies"}

        result = {
            "valid": True,
            "count": len(self.cookies),
            "important_cookies": {},
            "expired_cookies": []
        }

        # 检查重要的 cookies
        important_cookies = ['SID', 'HSID', 'SSID', 'APISID', 'SAPISID', 'LOGIN_INFO', 'PREF']
        cookies_dict = {cookie['name']: cookie for cookie in self.cookies}

        for name in important_cookies:
            if name in cookies_dict:
                result["important_cookies"][name] = "✅ 存在"
            else:
                result["important_cookies"][name] = "❌ 缺失"
                result["valid"] = False

        # 检查过期时间
        current_time = datetime.now().timestamp()
        for cookie in self.cookies:
            expires = cookie.get("expirationDate", -1)
            if expires > 0 and expires < current_time:
                result["expired_cookies"].append(cookie['name'])
                result["valid"] = False

        return result

    def print_cookie_info(self):
        """打印 cookies 的详细信息"""
        if not self.cookies:
            print("❌ 请先加载 cookies")
            return

        print(f"\n📊 Cookie 信息:")
        print(f"  数量: {len(self.cookies)}")

        print(f"\n🔑 重要 cookies:")
        important_cookies = ['SID', 'HSID', 'SSID', 'APISID', 'SAPISID', 'LOGIN_INFO', 'PREF']
        cookies_dict = {cookie['name']: cookie for cookie in self.cookies}

        for name in important_cookies:
            if name in cookies_dict:
                value = cookies_dict[name]['value']
                print(f"  ✅ {name}: {value[:20]}...")
            else:
                print(f"  ❌ {name}: 缺失")

        print(f"\n📅 过期时间:")
        for cookie in self.cookies:
            expires = cookie.get("expirationDate", -1)
            if expires > 0:
                expiry_date = datetime.fromtimestamp(expires)
                print(f"  {cookie['name']}: {expiry_date.strftime('%Y-%m-%d %H:%M:%S')}")

    @staticmethod
    def _normalize_same_site(same_site):
        """
        规范化 sameSite 值

        Args:
            same_site: 原始 sameSite 值

        Returns:
            str: 规范化的值
        """
        same_site = same_site.lower()
        if same_site == "unspecified":
            return "Lax"
        elif same_site == "no_restriction":
            return "None"
        return same_site.capitalize()


def main():
    """主函数 - 命令行接口"""
    import argparse

    parser = argparse.ArgumentParser(description="YouTube Cookies Manager")
    parser.add_argument("input", help="输入的 JSON 文件路径（BestCookier 导出）")
    parser.add_argument("--playwright", help="转换为 Playwright 格式并保存到指定路径")
    parser.add_argument("--netscape", help="转换为 Netscape 格式并保存到指定路径")
    parser.add_argument("--validate", action="store_true", help="验证 cookies 的完整性")
    parser.add_argument("--info", action="store_true", help="显示 cookies 的详细信息")

    args = parser.parse_args()

    # 创建管理器
    manager = YouTubeCookiesManager(args.input)

    # 加载 cookies
    if not manager.load_bestcookier_json(args.input):
        sys.exit(1)

    # 执行操作
    if args.playwright:
        if not manager.convert_to_playwright(args.playwright):
            sys.exit(1)

    if args.netscape:
        if not manager.convert_to_netscape(args.netscape):
            sys.exit(1)

    if args.validate:
        result = manager.validate_cookies()
        if result["valid"]:
            print("✅ Cookies 验证通过")
            print(f"  数量: {result['count']}")
            print(f"  重要 cookies: {result['important_cookies']}")
        else:
            print("❌ Cookies 验证失败")
            print(f"  重要 cookies: {result['important_cookies']}")
            if result['expired_cookies']:
                print(f"  已过期: {result['expired_cookies']}")
            sys.exit(1)

    if args.info:
        manager.print_cookie_info()

    # 如果没有指定任何操作，默认转换为两种格式
    if not any([args.playwright, args.netscape, args.validate, args.info]):
        default_playwright = Path(args.input).parent / "youtube_storage_state.json"
        default_netscape = Path(args.input).parent / "youtube_cookies.txt"

        manager.convert_to_playwright(str(default_playwright))
        manager.convert_to_netscape(str(default_netscape))


if __name__ == "__main__":
    main()
